name: FastAPI-GitHub-Heroku MLOps pipeline


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy Dashboard to Heroku
      uses: akhileshns/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
        heroku_app_name: ${{ secrets.DASHBOARD_HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        appdir: Dashboard  # specify the path to your dashboard directory      
        
