name: FastAPI-GitHub-Heroku MLOps pipeline


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Format
      run: |
        black API_script.py

    - name: Lint
      run: |
        pylint --extension-pkg-whitelist='pydantic' --disable=R,C API_script.py

    - name: Start FastAPI app
      run: |
        uvicorn API_script:app --host 127.0.0.1 --port 8000 &
        sleep 10 # Allow the API server to start

    - name: Run tests
      run: |
        pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        
    - name: Deploy Dashboard to Heroku
      uses: akhileshns/heroku-deploy@v3.12.13
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
        heroku_app_name: ${{ secrets.DASHBOARD_HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.DASHBOARD_HEROKU_EMAIL }}
        appdir: Dashboard  # specify the path to your dashboard directory      
        
